/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AudioViewer: typeof import('./../src/components/custom/AudioViewer.vue')['default']
    BabylonModelViewer: typeof import('./../src/components/custom/BabylonModelViewer.vue')['default']
    DxfViewer: typeof import('./../src/components/custom/DxfViewer.vue')['default']
    FileItemList: typeof import('@/components/FileItemList.vue')['default']
    RouteFileViewer: typeof import('@/components/RouteFileViewer.vue')['default']
    ImageViewer: typeof import('./../src/components/custom/ImageViewer.vue')['default']
    JsonViewer: typeof import('./../src/components/custom/JsonViewer.vue')['default']
    MarkdownViewer: typeof import('./../src/components/custom/MarkdownViewer.vue')['default']
    NBackTop: typeof import('naive-ui')['NBackTop']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NEllipsis: typeof import('naive-ui')['NEllipsis']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NFlex: typeof import('naive-ui')['NFlex']
    NImage: typeof import('naive-ui')['NImage']
    NInfiniteScroll: typeof import('naive-ui')['NInfiniteScroll']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSpin: typeof import('naive-ui')['NSpin']
    NSplit: typeof import('naive-ui')['NSplit']
    NTag: typeof import('naive-ui')['NTag']
    NTime: typeof import('naive-ui')['NTime']
    OfficeViewer: typeof import('./../src/components/custom/OfficeViewer.vue')['default']
    PlainTextViewer: typeof import('./../src/components/custom/PlainTextViewer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SphereImageViewer: typeof import('./../src/components/custom/SphereImageViewer.vue')['default']
    UnknownViewer: typeof import('./../src/components/custom/UnknownViewer.vue')['default']
    VideoViewer: typeof import('./../src/components/custom/VideoViewer.vue')['default']
  }
}
